export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import Header from './Components/Header';
import EmotionRootStyleRegistry from './Theme/EmotionRootStyleRegistry';
import ReduxProvider from './StateManagement/Provider';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <EmotionRootStyleRegistry key={''}>
          <ReduxProvider>
            <Header />
            <main style={{ marginTop: '7rem' }}>{children}</main>
          </ReduxProvider>
        </EmotionRootStyleRegistry>
      </body>
    </html>
  );
}
